# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_GWQZ9UJJ_R3WcpRQqj4gM_2VqveF5Y
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("images1.jpg")
cv2_imshow(rasm1)

rasm2=cv2.imread("images2.jpg")
cv2_imshow(rasm2)

rasm3=cv2.imread("images3.jpg")
cv2_imshow(rasm3)

rasm4=cv2.imread("images4.jpg")
cv2_imshow(rasm4)

rasm5=cv2.imread("images5.jpg")
cv2_imshow(rasm5)

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

oqqora=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

oqqora=cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

oqqora=cv2.cvtColor(rasm5,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)